In [15]:
import numpy as np

In [13]:
ndarr2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

In [14]:
print(ndarr2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print(ndarr2d[0, 1:2])

[2]


In [6]:
age = int(input('나이를 입력하세요: '))

if age>19:
    print('성인입니다')
else:
    print('미성년자입니다')
print(f'입력한 나이: {age}')

나이를 입력하세요: 20
성인입니다
입력한 나이: 20


In [15]:
age = int(input('나이를 입력하세요: '))

if age>19:
    print('성인입니다')
elif age>14:
    print('청소년입니다')
elif age>6:
    print('초딩입니다')
elif age>0:
    print('애기입니다')
else:
    print('커신입니다')
print(f'입력한 나이: {age}')

나이를 입력하세요: -44
커신입니다
입력한 나이: -44


In [18]:
id = input('아이디를 입력하세요: ')

if (length := len(id))<3:
    print(f'너무 짧아. (입력한 글자 수: {length})')
else:
    print(f"{id} 사용가능")

아이디를 입력하세요: 아
너무 짧아. (입력한 글자 수: 1)


In [22]:
jumin = input()
if int(jumin[6])%2==1:
    print('남자입니다')
else:
    print('여자입니다')

000000400000
여자입니다


In [21]:
num =